name: Feature Request
description: Request a new printer, resin, or feature
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: What do you want to add?
  - type: textarea
    attributes:
      label: Why is it needed?
